### ISSUE TITLE
Major security issue

### ISSUE THREAD

**Issue by kabassanov** [pluginsGLPI/geninventorynumber#42]
Hello,

There is a wrong test at the begging of the following function in inc/generation.class.php:

   static function preItemUpdate(CommonDBTM $item) {

      if (!Session::haveRight("plugin_geninventorynumber", UPDATE)) {
         return;
      }

It must be without "!" or people without UPDATE permission could change otherserial field...

Bug introduced in: https://github.com/pluginsGLPI/geninventorynumber/commit/35082f51afff24547e45405a0386009155875c8b#diff-bbd74a8dc9534a393f2e17a25556070f0d6a8270c6a300360277f265105965bb

**Comment by fralla2** [comment]
I read it differently...

If your current session don't have the "plugin_geninventorynumber" UPDATE right, it returns empty, therefore exiting the function and not executing the rest of the following commands...

**Comment by kabassanov** [comment]
I (an user of mine) simply removed auto-generated inventory number, so I'm pretty sure that the test is not ok...
Did you check on your side?

**Comment by fralla2** [comment]
Did you remove the otherserial directly on the asset' page (computer/monitor, etc) saving the form? If so, this is more a problem of the plugins not setting this field as locked.

I think the plugins UPDATE rights only test so that a user without that right could not use the plugins to regenerate new serials over the ones currently in place... It does not prevent manually editing the field inside the asset form it not locked.

At least that's my understanding of the code...

**Comment by fralla2** [comment]
But I agree both functions (preItemAdd and preItemUpdate) should be rewritten because I had to hack the preItemAdd part on my side so that plugins FusionInventory could generate the inventorynumber automatically.

**Comment by kabassanov** [comment]
Yes, the number has been removed directly from the asset page on form saving. As before the commit I mentioned in the previous post, the issue was not present, I think it is related.

**Comment by fralla2** [comment]
If the change was made directly on the asset page form, then it never goes through the plugins and therefore, never call this function... (Only a lock for this field in GLPI could have prevented this) and I do thing the plugin's should add a lock automatically after generating the inventorynumber.

As for the test inside the function of the plugins, I think it only prevent this a user without the "UPDATE" right to see and use this option on massive actions (Regenerate inventory number - Write over existing ones)

![image](https://user-images.githubusercontent.com/38400135/156801261-67b75b1a-1293-4d7e-ac7d-52218f8d7226.png)

**Comment by kabassanov** [comment]
Make a try... It does goes through this function, probably because assets update function in GLPI calls all plugins update functions. BTW I'm not sure that the plugin manages GLPI locks (have to check). Can you reproduce?

**Comment by fralla2** [comment]
> As before the commit I mentioned in the previous post, the issue was not present, I think it is related.

The commit you linked on top is dated from 2016 (6 years ago...)

**Comment by kabassanov** [comment]
> > As before the commit I mentioned in the previous post, the issue was not present, I think it is related.
> 
> The commit you linked on top is dated from 2016 (6 years ago...)

Yeah... I know. It seems that nobody remarked before...

**Comment by fralla2** [comment]
> Make a try... It does goes through this function, probably because assets update function in GLPI calls all plugins update functions. BTW I'm not sure that the plugin manages GLPI locks (have to check). Can you reproduce?

Sorry, after a second look, the function do get called but here's what I think is happening : 

Since you are in the asset form directly and change the otherserial field manually (this is a native glpi field already present without the plugins), when you save the form, the following things happens : 

1 - The geninventorynumber' preItemUpdate function get called because of the plugins' hook, and since your user don't have right to update, no change is made by the plugins (a new otherserial don't get generated over the current one)
--- Plugins pre_item_update phase now done, it goes to GLPI normal item_add phase --- 
2 - GLPI then goes to save the rest of the form changes (that includes your manually edited otherserial field) and since your user have rights through his profile to edit assets, and there is no lock on that particular field, GLPI itself write the new information over the current one (not the plugins)...

![image](https://user-images.githubusercontent.com/38400135/156806628-f83899f4-40e5-4260-925d-34bda3389570.png)

**Comment by fralla2** [comment]
You could test by changing the otherserial field with some text like "HELLO" and save the form.  

- If the word "HELLO" get saved, it's glpi that saved manually the information.
- It the otherserial becomes a generated one that follows your template, then it's the plugin's that overwritten it and must be investigated further

**Comment by kabassanov** [comment]
I will read  you post once again, but I'm sure it is GLPI that modifies the field and not the plugin. Simply with "!" inversion, the plugin function blocks somehow glpi update process and the update is rejected.

**Comment by kabassanov** [comment]
Hi,

Your reading of the situation is correct. Changing the if test will "only" prevent users with no rights from modifying field, but will allow users with rights to put any value they want and not only to regenerate a number, because the rollback mechanism in preItemUpdate won't be executed. 

The old **return array('noright')**  was the way to block users with modification rights in the form, but without update rights in the plugin when they try to change the field value. Really not sure that any other lock mechanism is implemented in this plugin.

It seems clear to me that even if "!" removal is not really the right way to solve the issue, it minimizes the risk, as only allowed people could change the field. If you have a better solution, please, let me know ;)

**Comment by kabassanov** [comment]
Stupid question: what will happen if we simply remove this Session:haveRight test? The only bug I see during tests is with massive actions, when a user with rights tries to change the field value manually: there are two contradictory messages: success and failure, but the field is not modified...
